# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('position', models.CharField(choices=[('QB', 'Quarterback'), ('HB', 'Running Back'), ('WR', 'Wide Receiver'), ('TE', 'Tight End'), ('OL', 'Offensive Line'), ('DL', 'Defensive Line'), ('ED', 'Edge'), ('LB', 'Inside Linebacker'), ('CB', 'Corner'), ('S', 'Safety')], max_length=2)),
                ('cap_hit', models.IntegerField()),
                ('on_team', models.BooleanField()),
                ('draft', models.BooleanField()),
                ('draft_round', models.IntegerField(null=True)),
            ],
        ),
    ]
