# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('position', models.CharField(choices=[('QB', 'Quarterback'), ('HB', 'Running Back'), ('WR', 'Wide Receiver'), ('TE', 'Tight End'), ('OL', 'Offensive Line'), ('DL', 'Defensive Line'), ('ED', 'Edge'), ('LB', 'Inside Linebacker'), ('CB', 'Corner'), ('S', 'Safety')], max_length=2)),
                ('cap_hit', models.IntegerField()),
                ('draft_round', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FreeAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('position', models.CharField(choices=[('QB', 'Quarterback'), ('HB', 'Running Back'), ('WR', 'Wide Receiver'), ('TE', 'Tight End'), ('OL', 'Offensive Line'), ('DL', 'Defensive Line'), ('ED', 'Edge'), ('LB', 'Inside Linebacker'), ('CB', 'Corner'), ('S', 'Safety')], max_length=2)),
                ('cap_hit', models.IntegerField()),
                ('on_team', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='draft',
        ),
        migrations.RemoveField(
            model_name='player',
            name='draft_round',
        ),
        migrations.RemoveField(
            model_name='player',
            name='on_team',
        ),
        migrations.AddField(
            model_name='player',
            name='cut_savings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
