# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 18:24
from __future__ import unicode_literals

from django.db import migrations
import csv

def add_team_player(apps, schema_editor):
    Player = apps.get_model('roster','Player')
    with open('roster/packers_roster.csv') as infile:
        reader = csv.reader(infile)
        for row in reader:
            Player.objects.create(first_name=row[0],last_name=row[1],position=row[2],cap_hit=0,
            cut_savings=0)

def add_free_agents(apps, schema_editor):
    FreeAgent = apps.get_model('roster', 'FreeAgent')
    with open('roster/free_agents.csv') as infile:
        reader = csv.reader(infile)
        for row in reader:
            FreeAgent.objects.create(first_name=row[0],last_name=row[1],position=row[2],cap_hit=0,on_team=row[4])
def add_draft(apps, schema_editor):
    DraftPlayer = apps.get_model('roster', 'DraftPlayer')
    with open('roster/draft.csv') as infile:
        reader = csv.reader(infile)
        for row in reader:
            DraftPlayer.objects.create(first_name=row[0],last_name=row[1],position=row[2],cap_hit=0,draft_round=row[4])


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0002_auto_20170208_2043'),
    ]

    operations = [
    migrations.RunPython(add_draft),
    migrations.RunPython(add_team_player),
    migrations.RunPython(add_free_agents),
    ]
