# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0004_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftplayer',
            name='college',
            field=models.CharField(default='university', max_length=100),
            preserve_default=False,
        ),
    ]
