# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0008_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='cut_savings',
            new_name='dead_money',
        ),
        migrations.RemoveField(
            model_name='account',
            name='cap',
        ),
        migrations.AddField(
            model_name='account',
            name='cap_max',
            field=models.FloatField(default=171.5),
        ),
    ]
