# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0010_auto_20170213_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeagent',
            name='modified_cost',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
