# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0011_freeagent_modified_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='offer',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
